apiVersion: v2
name: f5
description: Automatic backups of removable media to S3-compatible storage

type: application
version: 0.2.0
appVersion: "0.2.0"

keywords:
  - backup
  - s3
  - sd-card
  - homelab
