{{- if and (not .Values.aws.existingSecret) (include "f5.awsSecretEnabled" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "f5.awsSecretName" . }}
  labels:
    {{- include "f5.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.aws.config }}
  config: |
    {{- . | nindent 4 }}
  {{- end }}
  {{- with .Values.aws.credentials }}
  credentials: |
    {{- . | nindent 4 }}
  {{- end }}
  {{- with .Values.aws.caBundle }}
  ca-bundle.pem: |
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
